Python 3.8.3 (tags/v3.8.3:6f8c832, May 13 2020, 22:20:19) [MSC v.1925 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Current time : 10 : 18
Enter the Hour: 10
Enter the Minute: 19
ALARM ... ALARM ... 
Current time : 10 : 19
ALARM ... ALARM ... 
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 33
present time or local time is : 10 : 33
##################################################ALARAM#####################################################
Current time : 10 : 33
##################################################ALARAM#####################################################
WAKE UP DEAR
exited
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 36
Traceback (most recent call last):
  File "C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY", line 7, in <module>
    print ("present time or local time is : " + datetime.datetime.now())#strftime("%H") + " : " + datetime.datetime.today().strftime("%M"))
TypeError: can only concatenate str (not "datetime.datetime") to str
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 38
current date is:
2020-07-10 10:37:14.827053
##################################################ALARAM#####################################################
Current time : 10 : 38
##################################################ALARAM#####################################################
WAKE UP DEAR
exited
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 39
Traceback (most recent call last):
  File "C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY", line 6, in <module>
    print("current date is:"+date)
TypeError: can only concatenate str (not "datetime.datetime") to str
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 41
current date is:	
2020-07-10 10:40:56.421430
##################################################ALARAM#####################################################
Current time : 10 : 41
##################################################ALARAM#####################################################
WAKE UP DEAR
exited
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 42
current date is:	
2020-07-10 10:41:58.688851
##################################################ALARAM#####################################################
Traceback (most recent call last):
  File "C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY", line 11, in <module>
    print ("Current time : " + datetime.datetime.now())#strftime("%H") + " : " + datetime.datetime.today().strftime("%M"))
TypeError: can only concatenate str (not "datetime.datetime") to str
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 44
Traceback (most recent call last):
  File "C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY", line 6, in <module>
    print("current date is"+":"+date)
TypeError: can only concatenate str (not "datetime.datetime") to str
>>> 
==== RESTART: C:/Users/ahmed/OneDrive/Desktop/python programs/ALARAMCLOCK.PY ===
Enter the an Hour to set alaram : 10
Enter the Minute to set alaram: 46
current date is:
2020-07-10 10:45:43.478299
####################################ALARAM########################################
Current time : 10 : 46
####################################ALARAM########################################
WAKE UP DEAR
exited
>>> 